name: My first Workflow
on: workflow_dispatch
jobs:
  first_job:
  runs_on: ubuntu-latest
  steps:
    - name: print greeting
      run: echo "hello world"
    - name: print goodbye
      run: echo "bye done!!!!"
